### ISSUE TITLE
Rename "how to" section to "recipes"

### ISSUE THREAD

**Issue by joshka** [ratatui/ratatui-website#606]
A recipe is still "how to do" something, so I think it would work really well and keep the Ratatui theme going for a bit more fun without any sacrifice in meaning. Thoughts from the other @ratatui-org/maintainers

**Comment by kdheepak** [comment]
I like it! We might want to change "how-to/use-widgets" to "recipes/widgets" and make other similar changes if we move away from "how-to"

**Comment by joshka** [comment]
Doing this in https://github.com/ratatui-org/ratatui-website/tree/jm/recipes
Running into some problems with making the redirects work. Need to add the cloudflare adapter, and use hybrid rendering to make the redirects automatically work, and this fails to build correctly. (npm run dev runs, npm run build fails):

https://discord.com/channels/830184174198718474/1242301878994468916/1242301878994468916 in the astro discord has the deets.

```
19:38:24 [vite] ✓ built in 87ms
Cannot access 'ASTRO_VERSION' before initialization
  Stack trace:
    at createAstro (file:///Users/joshka/local/ratatui-website/dist/_worker.js/chunks/astro_CKohPv9b.mjs:393:26)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async BuildPipeline.retrieveManifest (file:///Users/joshka/local/ratatui-website/node_modules/astro/dist/core/build/pipeline.js:93:26)
    at async staticBuild (file:///Users/joshka/local/ratatui-website/node_modules/astro/dist/core/build/static-build.js:108:7)
    at async AstroBuilder.run (file:///Users/joshka/local/ratatui-website/node_modules/astro/dist/core/build/index.js:164:7)
husky - pre-commit script failed (code 1)
```

**Comment by joshka** [comment]
Addressed the blocker by just using many static redirects instead of dynamic redirects.

**Comment by kdheepak** [comment]
Do we need redirects? Maybe a 404 page that says check the site's sidebar or use the search bar would be good enough imo.

**Comment by joshka** [comment]
> Do we need redirects? Maybe a 404 page that says check the site's sidebar or use the search bar would be good enough imo.

Yeah, it's the polite thing to do. Not sure if anyone has linked to the site, but broken links suck and are pretty simple to handle.
